__title__ = '临床检验中心'
__version__ = '1.0.0'
__build__ = 0x030502
__build_string__ = 'Oct 28 00:00:00 2020 '
__django_version__ = '2.2'
__author__ = '上海陌芬信息技术有限公司'
__author_email__ = '348977654@qq.com'
__description__ = '质量管理系统'
__license__ = 'Apache 2.0'
__copyright_short__ = '2020 演示医院'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'http://sdh.suda.edu.cn'
